/* ════════════════════════════════════════════════════════════════════════
   pdfgen.js — minimalni izdelovalec PDF (brez zunanjih knjižnic, CSP 'self').
   Vgnezden podnabor pisave DejaVu Sans (slovenski znaki + €) za pravi izpis.
   API: var d=new PDFDoc(); d.addPage(); d.text(...); d.line(...); d.rect(...);
        d.image(jpegBytes,w,h,...); d.save('ime.pdf');
   ════════════════════════════════════════════════════════════════════════ */
(function () {
  var FONT_B64 = 'AAEAAAAMAIAAAwBATUFUSI+v2WAAAFPsAAACsk9TLzJq1BEdAABRIAAAAFZjbWFwZ9aH6gAAUXgAAAB0Z2FzcAAHAAcAAFPgAAAADGdseWZS7W94AAAAzAAARxRoZWFkJ1lMTwAASvQAAAA2aGhlYQ2fCNwAAFD8AAAAJGhtdHiySrMSAABLLAAABc5sb2NhMG4e5AAASAAAAALybWF4cAG4A8EAAEfgAAAAIG5hbWUn7T2+AABR7AAAAdRwb3N0/9sAWgAAU8AAAAAgAAIBNQAAAgAF1QADAAkAACUzFSMRMxEDIwMBNcvLyxSiFf7+BdX9cf6bAWUAAgDFA6oC6QXVAAMABwAAAREjESERIxEBb6oCJKoF1f3VAiv91QIrAAIAngAABhcFvgADAB8AAAEhAyELASETMwMhFSEDIRUhAyMTIQMjEyE1IRMhNSETBBf+3VQBJURoASRpoGcBOP6hUgE+/ptooGf+22ehaP7FAWBU/r4BaWYDhf6yA4f+YQGf/mGa/rKZ/mIBnv5iAZ6ZAU6aAZ8AAAMAqv7TBG0GFAAhACgALwAAASMDLgEnNR4BFxEuATU0Njc1MxUeARcVLgEnER4BFRQGBwMRDgEVFBYXET4BNTQmArRkAWnSambRb93J2sxkXa5TU69c49bj1mR0enHhf4F7/tMBLQItLbRAQQEByCSslqO8DuvoBB8bryouBP5VI7ScqcMPAwABmg1qWFZg1f5PEW5aWGgABQBx/+MHKQXwAAsAFwAjACcAMwAAASIGFRQWMzI2NTQmJzIWFRQGIyImNTQ2ASIGFRQWMzI2NTQmJTMBIxMyFhUUBiMiJjU0NgXRV2NjV1VjY1WeurudoLq7/JdWY2JXV2NkAzGg/FqgH568u5+fuboCkZSEgpWVgoOVf9y7u9vbu7zbAmGVgoSUlISBln/58wYN27u92tu8utwAAgCB/+MF/gXwAAkAMAAAAQ4BFRQWMzI2NwkBPgE3MwYCBwEjJw4BIyIANTQ2Ny4BNTQ2MzIWFxUuASMiBhUUFgHyW1XUoF+mSf57Afw7Qga6DGhdARf8j2jkg/H+zoaGMDLeuFOlVVeeRGmDOwMjUaFYksI/QAKP/fhZy3KE/v5+/uOTWVcBE9eA4WM/fTyixSQkti8xb1gzZwAAAQDFA6oBbwXVAAMAAAERIxEBb6oF1f3VAisAAAEAsP7yAnsGEgANAAABBgIVFBIXIyYCNTQSNwJ7hoKDhaCWlZSXBhLm/j7n5/475esBxuDfAcTsAAABAKT+8gJvBhIADQAAEzMWEhUUAgcjNhI1NAKkoJaVlZaghYODBhLs/jzf4P466+UBxefnAcIAAAEAPQJKA8MF8AARAAABDQEHJREjEQUnLQE3BREzESUDw/6ZAWc6/rBy/rA6AWf+mToBUHIBUATfwsNiy/6HAXnLYsPCY8sBef6HywABANkAAAXbBQQACwAAAREhFSERIxEhNSERA64CLf3TqP3TAi0FBP3Tqv3TAi2qAi0AAAEAnv8SAcMA/gAFAAA3MxUDIxPw06SBUv6s/sABQAAAAQBkAd8CfwKDAAMAABMhFSFkAhv95QKDpAABANsAAAGuAP4AAwAANzMVI9vT0/7+AAABAAD/QgKyBdUAAwAAATMBIwIIqv34qgXV+W0AAgCH/+MEjwXwAAsAFwAAASICERASMzISERACJzIAERAAIyIAERAAAoucnZ2cnZ2dnfsBCf73+/v+9wEJBVD+zf7M/s3+zQEzATMBNAEzoP5z/ob+h/5zAY0BeQF6AY0AAQDhAAAEWgXVAAoAADchEQU1JTMRIRUh/gFK/pkBZcoBSvykqgRzSLhI+tWqAAEAlgAABEoF8AAcAAAlIRUhNTYANz4BNTQmIyIGBzU+ATMyBBUUBgcGAAGJAsH8THMBjTNhTaeGX9N4etRY6AEURVsZ/vSqqqp3AZE6bZdJd5ZCQ8wxMujCXKVwHf7rAAEAnP/jBHMF8AAoAAABHgEVFAQhIiYnNR4BMzI2NTQmKwE1MzI2NTQmIyIGBzU+ATMyBBUUBgM/kaP+0P7oXsdqVMhtvse5pa62lZ6jmFO+cnPJWeYBDI4DJR/EkN3yJSXDMTKWj4SVpndwc3skJrQgINGyfKsAAAIAZAAABKQF1QACAA0AAAkBIQMzETMVIxEjESE1Awb+AgH+Nf7V1cn9XgUl/OMDzfwzqP6gAWDDAAABAJ7/4wRkBdUAHQAAEyEVIRE+ATMyABUUACEiJic1HgEzMjY1NCYjIgYH3QMZ/aAsWCz6AST+1P7vXsNoWsBrrcrKrVGhVAXVqv6SDw/+7urx/vUgIMsxMLacnLYkJgACAI//4wSWBfAACwAkAAABIgYVFBYzMjY1NCYBFS4BIyICAz4BMzIAFRQAIyAAERAAITIWAqSIn5+IiJ+fAQlMm0zI0w87smvhAQX+8OL+/f7uAVABG0ybAzu6oqG7u6GiugJ5uCQm/vL+71dd/u/r5v7qAY0BeQFiAaUeAAABAKgAAARoBdUABgAAEyEVASMBIagDwP3i0wH+/TMF1Vb6gQUrAAMAi//jBIsF8AALACMALwAAASIGFRQWMzI2NTQmJS4BNTQkMzIWFRQGBx4BFRQEIyIkNTQ2ExQWMzI2NTQmIyIGAouQpaWQkKal/qWCkQD/3t/+kYGSo/739/f+96RIkYOCk5OCg5ECxZqHh5qbhoeaViCygLPQ0LOAsiAixo/Z6OjZj8YBYXSCgnR0goIAAAIAgf/jBIcF8AAYACQAADc1HgEzMhITDgEjIgA1NAAzIAAREAAhIiYBMjY1NCYjIgYVFBbhTJxLyNMPOrJs4P77ARDiAQMBEf6x/uVMnAE+iJ+fiIifnx+4JCYBDQESVlwBD+vmARb+c/6G/p/+Wx4Cl7qiobu7oaK6AAACAPAAAAHDBCMAAwAHAAA3MxUjETMVI/DT09PT/v4EI/4AAgCe/xIBwwQjAAMACQAAEzMVIxEzFQMjE/DT09OkgVIEI/792az+wAFAAAABANkAXgXbBKYABgAACQIVATUBBdv7+AQI+v4FAgPw/pH+k7YB0aYB0QACANkBYAXbA6IAAwAHAAATIRUhFSEVIdkFAvr+BQL6/gOiqPCqAAEA2QBeBdsEpgAGAAATNQEVATUB2QUC+v4EBgPwtv4vpv4vtgFtAAACAJMAAAOwBfAAAwAkAAAlMxUjEyM1NDY/AT4BNTQmIyIGBzU+ATMyFhUUBg8BDgEHDgEVAYfLy8W/OFpaOTODbE+zYV7BZ7jfSFpYLycIBgb+/gGRmmWCVlk1XjFZbkZDvDk4wp9MiVZWLzUZFTw0AAACAIf+nAdxBaIACwBMAAABFBYzMjY1NCYjIgYBDgEjIiY1NDYzMhYXNTMRPgE1NCYnJiQjIgYHBgIVFBIXFgQzMjY3FwYEIyIkJyYCNTQSNzYkMzIEFx4BFRAABQL6jnx7jZB6eY8CITybZ6zX2KtnnDuPkqU/QGj+1bB74mCdsXNtaQEUnYH5aFp9/tmYuf64gICGiH6BAVK91AFre0tP/sL+6AIZj6OkjoylpP5ITUn5yMj6S0yD/SAW37FrvFCDi0FAZv61wZ/+6mpobVdRb2Fng319AUm9tgFKfX+HrqBi5nv++f7QBgACABAAAAVoBdUAAgAKAAAJASEBMwEjAyEDIwK8/u4CJf575QI50oj9X4jVBQ79GQOu+isBf/6BAAMAyQAABOwF1QAIABEAIAAAAREhMjY1NCYjAREhMjY1NCYjJSEyFhUUBgceARUUBCMhAZMBRKOdnaP+vAErlJGRlP4LAgTn+oB8laX+8Pv96ALJ/d2Hi4yFAmb+Pm9ycXCmwLGJohQgy5jI2gAAAQBz/+MFJwXwABkAAAEVLgEjIAAREAAhMjY3FQ4BIyAAERAAITIWBSdm54L/AP7wARABAILnZmrthP6t/noBhgFThu0FYtVfXv7H/tj+2f7HXl/TSEgBnwFnAWgBn0cAAgDJAAAFsAXVAAgAEQAAAREzIAAREAAhJSEgABEQACkBAZP0ATUBH/7h/sv+QgGfAbIBlv5o/lD+YQUv+3cBGAEuASwBF6b+l/6A/n7+lgABAMkAAASLBdUACwAAEyEVIREhFSERIRUhyQOw/RoCx/05Avj8PgXVqv5Gqv3jqgABAMkAAAQjBdUACQAAEyEVIREhFSERI8kDWv1wAlD9sMoF1ar+SKr9NwABAHP/4wWLBfAAHQAAJREhNSERBgQjIAAREAAhMgQXFS4BIyAAERAAITI2BMP+tgISdf7moP6i/nUBiwFekgEHb3D8i/7u/u0BEwESa6jVAZGm/X9TVQGZAW0BbgGZSEbXX2D+zv7R/tL+ziUAAAEAyQAABTsF1QALAAATMxEhETMRIxEhESPJygLeysr9IsoF1f2cAmT6KwLH/TkAAAEAyQAAAZMF1QADAAATMxEjycrKBdX6KwAAAf+W/mYBkwXVAAsAABMzERAGKwE1MzI2NcnKzeNNP4ZuBdX6k/7y9KqWwgABAMkAAAVqBdUACgAAEzMRASEJASEBESPJygKeAQT9GwMa/vb9M8oF1f2JAnf9SPzjAs/9MQABAMkAAARqBdUABQAAEzMRIRUhycoC1/xfBdX61aoAAAEAyQAABh8F1QAMAAATIQkBIREjEQEjAREjyQEtAX0BfwEtxf5/y/5/xAXV/AgD+PorBR/8AAQA+uEAAAEAyQAABTMF1QAJAAATIQERMxEhAREjyQEQApbE/vD9asQF1fsfBOH6KwTh+x8AAAIAc//jBdkF8AALABcAAAEiABEQADMyABEQACcgABEQACEgABEQAAMn3P79AQPc3AEB/v/cAToBeP6I/sb+xf6HAXkFTP64/uX+5v64AUgBGgEbAUik/lv+nv6f/lsBpAFiAWIBpQAAAgDJAAAEjQXVAAgAEwAAAREzMjY1NCYjJSEyBBUUBCsBESMBk/6NmpqN/jgByPsBAf7/+/7KBS/9z5KHhpKm49vd4v2oAAIAc/74BdkF8AALAB0AAAEiABEQADMyABEQABMBIycOASMgABEQACEgABEQAgMn3P79AQPc3AEB/v8/AQr03SEjEP7F/ocBeQE7AToBeNEFTP64/uX+5v64AUgBGgEbAUj6z/7d7wICAaUBYQFiAaX+W/6e/vz+jgAAAgDJAAAFVAXVABMAHAAAAR4BFxMjAy4BKwERIxEhIBYVFAYBETMyNjU0JiMDjUF7Ps3Zv0qLeNzKAcgBAPyD/Yn+kpWVkgK8FpB+/mgBf5Zi/YkF1dbYjboCT/3uh4ODhQABAIf/4wSiBfAAJwAAARUuASMiBhUUFh8BHgEVFAQhIiYnNR4BMzI2NTQmLwEuATU0JDMyFgRIc8xfpbN3pnri1/7d/udq74B77HKtvIeae+LKARf1adoFpMU3NoB2Y2UfGSvZttngMC/QRUaIfm58HxgtwKvG5CYAAAH/+gAABOkF1QAHAAADIRUhESMRIQYE7/3uy/3uBdWq+tUFKwAAAQCy/+MFKQXVABEAABMzERQWMzI2NREzERAAISAAEbLLrsPCrsv+3/7m/uX+3wXV/HXw09PwA4v8XP7c/tYBKgEkAAABABAAAAVoBdUABgAAIQEzCQEzAQJK/cbTAdkB2tL9xwXV+xcE6forAAABAEQAAAemBdUADAAAEzMJATMJATMBIwkBI0TMAToBOeMBOgE5zf6J/v7F/sL+BdX7EgTu+xIE7vorBRD68AAAAQA9AAAFOwXVAAsAABMzCQEzCQEjCQEjAYHZAXMBddn+IAIA2f5c/lnaAhUF1f3VAiv9M/z4Anv9hQMdAAAB//wAAATnBdUACAAAAzMJATMBESMRBNkBngGb2f3wywXV/ZoCZvzy/TkCxwAAAQBcAAAFHwXVAAkAABMhFQEhFSE1ASFzBJX8UAPH+z0DsPxnBdWa+2+qmgSRAAEAsP7yAlgGFAAHAAATIRUjETMVIbABqPDw/lgGFI/5/I8AAAEAAP9CArIF1QADAAATASMBqgIIqv34BdX5bQaTAAEAx/7yAm8GFAAHAAABESE1MxEjNQJv/ljv7wYU+N6PBgSPAAEA2QOoBdsF1QAGAAAJASMJASMBA7wCH8n+SP5IyQIfBdX90wGL/nUCLQAAAf/s/h0EFP6sAAMAAAEVITUEFPvY/qyPjwABAKoE8AKJBmYAAwAACQEjAQFvARqZ/roGZv6KAXYAAAIAe//jBC0EewAKACUAAAEiBhUUFjMyNj0BNxEjNQ4BIyImNTQ2MyE1NCYjIgYHNT4BMzIWAr7frIFvmbm4uD+8iKzL/fsBAqeXYLZUZb5a8/ACM2Z7YnPZtClM/YGqZmHBor3AEn+LLi6qJyf8AAACALr/4wSkBhQACwAcAAABNCYjIgYVFBYzMjYBPgEzMgAREAIjIiYnFSMRMwPlp5KSp6eSkqf9jjqxe8wA///Me7E6ubkCL8vn58vL5+cCUmRh/rz++P74/rxhZKgGFAABAHH/4wPnBHsAGQAAARUuASMiBhUUFjMyNjcVDgEjIgAREAAhMhYD506dULPGxrNQnU5NpV39/tYBLQEGVaIENawrK+PNzeMrK6okJAE+AQ4BEgE6IwAAAgBx/+MEWgYUABAAHAAAAREzESM1DgEjIgIREAAzMhYBFBYzMjY1NCYjIgYDori4OrF8y/8A/8t8sf3Hp5KSqKiSkqcDtgJe+eyoZGEBRAEIAQgBRGH+Fcvn58vL5+cAAgBx/+MEfwR7ABQAGwAAARUhHgEzMjY3FQ4BIyAAERAAMzIABy4BIyIGBwR//LIMzbdqx2Jj0Gv+9P7HASn84gEHuAKliJq5DgJeWr7HNDSuKiwBOAEKARMBQ/7dxJe0rp4AAAEALwAAAvgGFAATAAABFSMiBh0BIRUhESMRIzUzNTQ2MwL4sGNNAS/+0bmwsK69BhSZUGhjj/wvA9GPTrurAAACAHH+VgRaBHsACwAoAAABNCYjIgYVFBYzMjYXEAIhIiYnNR4BMzI2PQEOASMiAhEQEjMyFhc1MwOipZWUpaWUlaW4/v76YaxRUZ5StbQ5snzO/PzOfLI5uAI9yNzcyMfc3Ov+4v7pHR6zLCq9v1tjYgE6AQMBBAE6YmOqAAABALoAAARkBhQAEwAAAREjETQmIyIGFREjETMRPgEzMhYEZLh8fJWsublCs3XBxgKk/VwCnp+evqT9hwYU/Z5lZO8AAAIAwQAAAXkGFAADAAcAABMzESMRMxUjwbi4uLgEYPugBhTpAAL/2/5WAXkGFAALAA8AABMzERQGKwE1MzI2NREzFSPBuKO1RjFpTLi4BGD7jNbAnGGZBijpAAEAugAABJwGFAAKAAATMxEBMwkBIwERI7q5AiXr/a4Ca/D9x7kGFPxpAeP99P2sAiP93QABAMEAAAF5BhQAAwAAEzMRI8G4uAYU+ewAAAEAugAABx0EewAiAAABPgEzMhYVESMRNCYjIgYVESMRNCYjIgYVESMRMxU+ATMyFgQpRcCCr765cnWPprlyd42mubk/sHl6qwOJfHb14v1cAp6hnL6k/YcCnqKbv6P9hwRgrmdifAAAAQC6AAAEZAR7ABMAAAERIxE0JiMiBhURIxEzFT4BMzIWBGS4fHyVrLm5QrN1wcYCpP1cAp6fnr6k/YcEYK5lZO8AAgBx/+MEdQR7AAsAFwAAASIGFRQWMzI2NTQmJzIAERAAIyIAERAAAnOUrKuVk6ysk/ABEv7u8PH+7wERA9/nycnn6MjH6Zz+yP7s/u3+xwE5ARMBFAE4AAIAuv5WBKQEewAQABwAACURIxEzFT4BMzIAERACIyImATQmIyIGFRQWMzI2AXO5uTqxe8wA///Me7ECOKeSkqenkpKnqP2uBgqqZGH+vP74/vj+vGEB68vn58vL5+cAAAIAcf5WBFoEewALABwAAAEUFjMyNjU0JiMiBgEOASMiAhEQADMyFhc1MxEjAS+nkpKoqJKSpwJzOrF8y/8A/8t8sTq4uAIvy+fny8vn5/2uZGEBRAEIAQgBRGFkqvn2AAEAugAAA0oEewARAAABLgEjIgYVESMRMxU+ATMyFhcDSh9JLJynubk6uoUTLhwDtBIRy779sgRgrmZjBQUAAQBv/+MDxwR7ACcAAAEVLgEjIgYVFBYfAR4BFRQGIyImJzUeATMyNjU0Ji8BLgE1NDYzMhYDi06oWomJYpQ/xKX32FrDbGbGYYKMZatAq5jgzma0BD+uKChUVEBJIQ4qmYmctiMjvjU1WVFLUCUPJJWCnqweAAEANwAAAvIFngATAAABESEVIREUFjsBFSMiJjURIzUzEQF3AXv+hUtzvb3VooeHBZ7+wo/9oIlOmp/SAmCPAT4AAAIArv/jBFgEewATABQAABMRMxEUFjMyNjURMxEjNQ4BIyImAa64fHyVrbi4Q7F1wcgBzwG6Aqb9YZ+fvqQCe/ugrGZj8AOoAAEAPQAABH8EYAAGAAATMwkBMwEjPcMBXgFew/5c+gRg/FQDrPugAAABAFYAAAY1BGAADAAAEzMbATMbATMBIwsBI1a45uXZ5uW4/tvZ8fLZBGD8lgNq/JYDavugA5b8agAAAQA7AAAEeQRgAAsAAAkCIwkBIwkBMwkBBGT+awGq2f66/rrZAbP+ctkBKQEpBGD93/3BAbj+SAJKAhb+cQGPAAEAPf5WBH8EYAAPAAAFDgErATUzMjY/AQEzCQEzApNOlHyTbExUMyH+O8MBXgFew2jIeppIhlQETvyUA2wAAQBYAAAD2wRgAAkAABMhFQEhFSE1ASFxA2r9TAK0/H0CtP1lBGCo/NuTqAMlAAEBAP6yBBcGFAAkAAAFFSMiJj0BNCYrATUzMjY9ATQ2OwEVIyIGHQEUBgceAR0BFBYzBBc++alsjj09j2up+T5EjVZbbm9aVo2+kJTd75d0j3OV8N2Tj1iN+J2OGRuOnPiNWAABAQT+HQGuBh0AAwAAAREjEQGuqgYd+AAIAAAAAQEA/rIEFwYUACQAAAUzMjY9ATQ2Ny4BPQE0JisBNTMyFh0BFBY7ARUjIgYdARQGKwEBAEaMVVpvb1pVjEY/+adsjj4+jmyn+T++Vo/4nI4bGY6d+I5Xj5Pd8JVzj3SX792UAAEA2QHTBdsDMQAdAAABFQ4BIyInJicmJyYjIgYHNT4BMzIXFhcWFxYzMjYF22mzYW6SCwUHD5teWKxiabNhbpMKBQgOm15WqQMxsk9EOwQCAwU+TVOyT0U8BAIDBT5MAAIBNf6LAgAEYAADAAkAAAEjNTMRIxETMxMCAMvLyxWiFANi/vorAo8BZf6bAAACAKz+xwQjBZgABgAhAAAlEQ4BFRQWARUuAScDPgE3FQ4BBxEjESYAERAANxEzEx4BAqaTpKQCEEqIRAFGiUhBiU1m8f73AQnxZgFJiYMDWBLiuLniA6GsKSoD/KAFKieqHiMH/uQBIBQBMwEBAQIBMhYBH/7hBCEAAAEAgQAABGIF8AAbAAABFS4BIyIGHQEhFSERIRUhNTMRIzUzNRA2MzIWBE5MiD2UdAGH/nkCLfwf7MfH1ug9lwW0tikpm9TXj/4vqqoB0Y/uAQXzHwAAAgBeAFIEvASyACMALwAAATcXBx4BFRQGBxcHJw4BIyImJwcnNy4BNTQ2Nyc3Fz4BMzIWEzQmIyIGFRQWMzI2A3vPcs4lJCYo0XLPO3Q9Ong9z3HPJSUmJs9zzzd0QDx1XJtycJ6dcXGcA+HRc847dz4/cznPcc8oJiUlz3POPnY6QHQ4znPPJyUk/nxwmppwcpydAAEAUgAABMMF1QAYAAABIREjESE1ITUnITUhATMJATMBIRUhBxUhBI3+Y8n+YAGgVP60AQj+w74BewF5v/7CAQj+tVQBnwHH/jkBx3szm3sCSv1EArz9tnubMwAAAgEE/qIBrgWYAAMABwAAAREjERMRIxEBrqqqqgGY/QoC9gQA/QoC9gAAAgBc/z0DogXwAAsAPgAAAQ4BFRQWFz4BNTQmExUuASMiBhUUFxYXHgEVFAYHHgEVFAYjIiYnNR4BMzI2NTQvAS4BNTQ2Ny4BNTQ2MzIWAXs/Pov6Pz6PzFOPOGFszhoO04NcXT45zK1JmlhXlDpmcd0Z1oBdWzs7yKZJmQOoLlouTIWHLVsuS4gCk6QnJ1BHWnMPCHeaZVqMNTRtQI6oHR2kJydUTGZ7DniZZluPMSxwRYKfHQACANcFRgMpBhAAAwAHAAABMxUjJTMVIwJey8v+ecvLBhDKysoAAAMBGwAABuUFzQAXAC8ASQAAATIEFxYSFRQCBwYEIyIkJyYCNTQSNzYkFyIGBw4BFRQWFx4BMzI2Nz4BNTQmJy4BFxUuASMiBhUUFjMyNjcVDgEjIiY1NDYzMhYEAJgBB21tbGxtbf75mJj++W1tbGxtbQEHmIPiXl5gYF5e4oOE415dXV5cXuOnQoJClaerm0B6QkOJRtj7+9hJiAXNbm1t/vqamP77bW1ubm1tAQWYmgEGbW1uZ15eXuWCgeNeXl9fXl3ig4XjXV5e9YEhIK+dn64fIn8dHPTQ0fIcAAMAcwHVAzsF8AADAB4AKQAAEyEVIQERIzUOASMiJjU0NjsBNTQmIyIGBzU+ATMyFgUiBhUUFjMyNj0BiwKw/VACrpUskF2AmL+8tnV1PohESZFFt7P+7KF+YlJoggJQewK4/kBwP0SHcYeKBFtbIiJ/HByw8ENPQE2Qch0AAAIAngCNBCUEIwAGAA0AAAEVCQEVATUTFQkBFQE1BCX+0wEt/isj/tMBLf4rBCO//vT+9L8BolIBor/+9P70vwGiUgAAAQDZAR8F2wNeAAUAABMhESMRIdkFAqj7pgNe/cEBlQABAGQB3wJ/AoMAAwAAEyEVIWQCG/3lAoOkAAQBGwAABuUFzQAXAC8AOABMAAABIgYHDgEVFBYXHgEzMjY3PgE1NCYnLgEnMgQXFhIVFAIHBgQjIiQnJgI1NBI3NiQTIxEzMjY1NCYnMhYVFAYHHgEfASMnLgErAREjEQQAg+JeXmBgXl7ig4TjXl1dXlxe44SYAQdtbWxsbW3++ZiY/vltbWxsbW0BB317e25XWGawrmlgGEMuiayBO0k2QpsFZl5eXuWCgeNeXl9fXl3ig4XjXV5eZ25tbf76mpj++21tbm5tbQEFmJoBBm1tbv5i/uw+S0w/Z3d5VnARCE1J39FgM/6cA0QAAQDVBWIDKwX2AAMAABMhFSHVAlb9qgX2lAACAMMDdQM9BfAACwAaAAABIgYVFBYzMjY1NCYnMhYXHgEVFAYjIiY1NDYCAFBublBQbm9PQHYrLi65hoe0uAVvb1BPbW1PT3CBMS4tckKEt7SHhroAAAIA2QAABdsFBAALAA8AAAERIRUhESMRITUhEQEhFSEDrgIt/dOo/dMCLf3TBQL6/gUE/n2q/n0Bg6oBg/umqgABAF4CnAK0BfAAGAAAASEVITU2NwA1NCYjIgYHNT4BMzIWFRQBBgEMAaj9qiI/AVhoVTR6SE2FOZGu/rU4Aw5ybh84ATFeQlEjI3scHIRsi/7kMAABAGICjQLNBfAAKAAAAR4BFRQGIyImJzUeATMyNjU0JisBNTMyNjU0JiMiBgc1PgEzMhYVFAYCDFxlvrE5fUY0d0NteG9sVl5eYWRfKGZRSYA3kKlaBGASbVJ8hhUUeRsaT0ZKTGw/PDo9EhdzERJ2Y0VgAAEBcwTuA1IGZgADAAABMwEjAovH/rqZBmb+iAABAK7+VgTlBGAAIAAAExEzERQWMzI2NREzERQWMzI2NxUOASMiJicOASMiJicRrriKh5SVuCMlCSAcKUkjRVIPMpFiZo8q/lYGCv1IkZSoqAKN/KI8OQsMlBcWTlBPT05O/dcAAQCe/zsEOQXVAA0AAAEhESMRIxEjES4BNTQkAnkBwI2+jtfrAQQF1flmBh/54QNOEd24vugAAQDbAkgBrgNGAAMAABMzFSPb09MDRv4AAQEj/nUCwQAAABMAACEeARUUBiMiJic1HgEzMjY1NCYnAlQ3Nnh2LlcrIkovOzwrLT5pMFlbDAyDEQ8wLh5XPQAAAQCJApwCxQXfAAoAABMzEQc1NzMRMxUhnMzf5onN/dcDCgJjKXQn/StuAAADAGAB1QNkBfAAAwAPABsAABMhFSEBMhYVFAYjIiY1NDYXIgYVFBYzMjY1NCaLArD9UAFYs87Os7PQ0LNpfn9oaX18AlB7BBvdv7/b3L6/3XOhiIWgoIWJoAACAMEAjQRIBCMABgANAAATARUBNQkBJQEVATUJAcEB1f4rAS3+0wGyAdX+KwEt/tMEI/5eUv5evwEMAQy//l5S/l6/AQwBDP//AIn/4wd/BfAQJgB5AAAQJwFYBIv9ZBAHAVcDNQAA//8Aif/jBz8F8BAmAHkAABAnAHIEi/1kEAcBVwM1AAD//wBi/+MHfwXwECYAcwAAECcBWASL/WQQBwFXAzUAAAACAI/+bgOsBGAAIAAkAAABMxUUBg8BDgEVFBYzMjY3FQ4BIyImNTQ2PwE+ATc+ATUTIzUzAfS+N1paOjODbU60YF7AZ7jgSVlYMCYIBwbEysoCz5xlgldYNV4xWW5GQ7w5OMKfTIlWVi81GRU8NgEO/v//ABAAAAVoB2sSJgAiAAAQBwFyBLwBdf//ABAAAAVoB2sSJgAiAAAQBwFwBLwBdf//ABAAAAVoB20SJgAiAAAQBwFzBLwBdf//ABAAAAVoB14SJgAiAAAQBwFxBLwBdf//ABAAAAVoB04SJgAiAAAQBwFvBLwBdQADABAAAAVoB20ACwAOACEAAAE0JiMiBhUUFjMyNgMBIQEuATU0NjMyFhUUBgcBIwMhAyMDVFk/QFdYPz9ZmP7wAiH+WD0+n3NyoT88AhTSiP1fiNUGWj9ZV0E/WFj+8/0ZA04pc0lzoKFyRnYp+osBf/6BAAIACAAAB0gF1QAPABMAAAEVIREhFSERIRUhESEDIwEXASERBzX9GwLH/TkC+Pw9/fCgzQJxi/62AcsF1ar+Rqr946oBf/6BBdWe/PADEAD//wBz/nUFJwXwEiYAJAAAEAcAeAEtAAD//wDJAAAEiwdrEiYAJgAAEAcBcgSeAXX//wDJAAAEiwdrEiYAJgAAEAcBcASeAXX//wDJAAAEiwdtEiYAJgAAEAcBcwSeAXX//wDJAAAEiwdOEiYAJgAAEAcBbwSeAXX//wA7AAABugdrEiYAKgAAEAcBcgMvAXX//wCiAAACHwdrEiYAKgAAEAcBcAMvAXX////+AAACYAdtEiYAKgAAEAcBcwMvAXX//wAGAAACWAdOEiYAKgAAEAcBbwMvAXUAAgAKAAAFugXVAAwAGQAAEyEgABEQACkBESM1MxMRIRUhETMgABEQACHTAaABsQGW/mn+UP5gycnLAVD+sPMBNQEf/uH+ywXV/pf+gP5+/pYCvJAB4/4dkP3qARgBLgEsARcA//8AyQAABTMHXhImAC8AABAHAXEE/gF1//8Ac//jBdkHaxImADAAABAHAXIFJwF1//8Ac//jBdkHaxImADAAABAHAXAFJwF1//8Ac//jBdkHbRImADAAABAHAXMFJwF1//8Ac//jBdkHXhImADAAABAHAXEFJwF1//8Ac//jBdkHThImADAAABAHAW8FJwF1AAEBGQA/BZwExQALAAAJAgcJAScJATcJAQWc/jcByXf+Nf41dgHI/jh2AcsBywRM/jX+N3kBy/41eQHJAct5/jUBywAAAwBm/7oF5QYXAAkAEwArAAAJAR4BMzIAETQmJy4BIyIAERQWFwcmAjUQACEyFhc3FwcWEhUQACEiJicHJwS2/TM+oV/cAQEneT2hX9z+/Scnhk5PAXkBO4LdV6Jmqk5Q/oj+xoDdW6JnBFj8skBDAUgBGnC4uEBD/rj+5XC8RJ5mAQigAWIBpU1Lv1nGZ/72nv6f/ltLS79Y//8Asv/jBSkHaxImADYAABAHAXIE7gF1//8Asv/jBSkHaxImADYAABAHAXAE7gF1//8Asv/jBSkHbRImADYAABAHAXME7gF1//8Asv/jBSkHThImADYAABAHAW8E7gF1/////AAABOcHaxImADoAABAHAXAEcwF1AAIAyQAABI0F1QAMABUAABMzETMyBBUUBCsBESMTETMyNjU0JiPJyv77AQH+//v+ysr+jZqZjgXV/vjh3Nzi/q4EJ/3RkoaGkQAAAQC6/+MErAYUAC8AABM0NjMyFhcOARUUFh8BHgEVFAYjIiYnNR4BMzI2NTQmLwEuATU0NjcuASMiBhURI7rv2tDbA5eoOkE5pmDh00CISVCMQXR4O2VcYFenlwiDcYKIuwRxyNvo4AhzYC9RKiVqjmSstxkYpB4dX1s/VD43O4dbf6wdZ3CLg/uTAP//AHv/4wQtBmYSJgBCAAAQBgBBUgD//wB7/+MELQZmEiYAQgAAEAYAdFIA//8Ae//jBC0GZhImAEIAABAGAUJSAP//AHv/4wQtBjcSJgBCAAAQBgFHUgD//wB7/+MELQYQEiYAQgAAEAYAaFIA//8Ae//jBC0HBhImAEIAABAGAUVSAAADAHv/4wdvBHsABgAzAD4AAAEuASMiBgcDPgEzMgAdASEeATMyNjcVDgEjIiYnDgEjIiY1NDYzITU0JiMiBgc1PgEzMhYDIgYVFBYzMjY9AQa2AaWJmbkORErUhOIBCPyyDMy3aMhkZNBqp/hNSdiPvdL9+wECp5dgtlRlvlqO1e/frIFvmbkClJe0rp4BMFpe/t36Wr/INTWuKix5d3h4u6i9wBJ/iy4uqicnYP4YZntic9m0KQD//wBx/nUD5wR7EiYARAAAEAcAeACPAAD//wBx/+MEfwZmEiYARgAAEAcAQQCLAAD//wBx/+MEfwZmEiYARgAAEAcAdACLAAD//wBx/+MEfwZmEiYARgAAEAcBQgCLAAD//wBx/+MEfwYQEiYARgAAEAcAaACLAAD////HAAABpgZmECcAQf8dAAASBgDxAAD//wCQAAACbwZmECcAdP8dAAASBgDxAAD////eAAACXAZmEiYA8QAAEAcBQv8dAAD////0AAACRgYQEiYA8QAAEAcAaP8dAAAAAgBx/+MEdQYUAA4AKAAAAS4BIyIGFRQWMzI2NTQmExYSFRQAIyIAETQAMzIWFycFJyUnMxclFwUDRjJYKae5rpKRrjYJfnL+5Obn/uUBFN0SNCqf/sEhARm15H8BTSH+2QOTERDYw7ze3rx6vAEmj/7grf/+yQE3AP/6ATcFBbRrY1zMkW9hYgD//wC6AAAEZAY3EiYATwAAEAcBRwCYAAD//wBx/+MEdQZmEiYAUAAAEAYAQXMA//8Acf/jBHUGZhImAFAAABAGAHRzAP//AHH/4wR1BmYSJgBQAAAQBgFCcwD//wBx/+MEdQY3EiYAUAAAEAYBR3MA//8Acf/jBHUGEBImAFAAABAGAGhzAAADANkAlgXbBG8AAwAHAAsAAAEzFSMRMxUjASEVIQLf9vb29v36BQL6/gRv9v4S9QJBqgAAAwBI/6IEnAS8AAkAEwArAAAJAR4BMzI2NTQmJy4BIyIGFRQWFwcuATUQADMyFhc3FwceARUQACMiJicHJwOJ/hkpZ0GTrBRcKmc+l6kTFH02NgER8V2fQ4tfkjU2/u7wYKE/i2ADIf2wKijoyE91mikp69NIbi6XTcV3ARQBODM0qE+zTcZ4/u3+xzQzqE7//wCu/+MEWAZmEiYAVgAAEAYAQXsA//8Arv/jBFgGZhImAFYAABAGAHR7AP//AK7/4wRYBmYSJgBWAAAQBgFCewD//wCu/+MEWAYQEiYAVgAAEAYAaHsA//8APf5WBH8GZhImAFoAABAGAHReAAACALr+VgSkBhQAEAAcAAAlESMRMxE+ATMyABEQAiMiJgE0JiMiBhUUFjMyNgFzubk6sXvMAP//zHuxAjinkpKnp5KSp6j9rge+/aJkYf68/vj++P68YQHry+fny8vn5///AD3+VgR/BhASJgBaAAAQBgBoXgD//wAQAAAFaAcxECcAbwC8ATsSBgAiAAD//wB7/+MELQX2ECYAb0oAEgYAQgAA//8AEAAABWgHkhAnAUQAzgFKEgYAIgAA//8Ae//jBC0GHxAmAURP1xIGAEIAAP//ABD+dQWlBdUSJgAiAAAQBwFGAuQAAP//AHv+dQSABHsSJgBCAAAQBwFGAb8AAP//AHP/4wUnB2sSJgAkAAAQBwFwBS0Bdf//AHH/4wPnBmYSJgBEAAAQBwB0AIkAAP//AHP/4wUnB20QJwFzBUwBdRIGACQAAP//AHH/4wPnBmYSJgBEAAAQBwFCAKQAAP//AHP/4wUnB1AQJwF2BUwBdRIGACQAAP//AHH/4wPnBhQQJwFJBKQAABIGAEQAAP//AHP/4wUnB20SJgAkAAAQBwF0BS0Bdf//AHH/4wPnBmYSJgBEAAAQBwFDAIkAAP//AMkAAAWwB20QJwF0BOwBdRIGACUAAP//AHH/4wXbBhQSJgBFAAAQBwFuBRQAAP//AAoAAAW6BdUQBgCQAAAAAgBx/+ME9AYUABgAJAAAAREhNSE1MxUzFSMRIzUOASMiAhEQADMyFgEUFjMyNjU0JiMiBgOi/roBRriamrg6sXzL/wD/y3yx/cenkpKoqJKSpwO2AU59k5N9+vyoZGEBRAEIAQgBRGH+Fcvn58vL5+f//wDJAAAEiwczEiYAJgAAEAcAbwChAT3//wBx/+MEfwX2ECcAbwCWAAASBgBGAAD//wDJAAAEiwdtECcBdQShAXUSBgAmAAD//wBx/+MEfwZIECcBRACWAAASBgBGAAD//wDJAAAEiwdQECcBdgSeAXUSBgAmAAD//wBx/+MEfwYUECcBSQSWAAASBgBGAAD//wDJ/nUEjQXVEiYAJgAAEAcBRgHMAAD//wBx/nUEfwR7EiYARgAAEAcBRgF4AAD//wDJAAAEiwdnEiYAJgAAEAcBdASmAW///wBx/+MEfwZhEiYARgAAEAcBQwCU//v//wBz/+MFiwdtECcBcwVcAXUSBgAoAAD//wBx/lYEWgZmECYBQmgAEgYASAAA//8Ac//jBYsHbRImACgAABAHAXUFGwF1//8Acf5WBFoGSBImAEgAABAHAUQAiwAA//8Ac//jBYsHUBAnAXYFXAF1EgYAKAAA//8Acf5WBFoGFBAnAUkEagAAEgYASAAA//8Ac/4BBYsF8BAnAUwFXv/tEgYAKAAA//8Acf5WBFoGNBAnAUsD4AEMEgYASAAA//8AyQAABTsHbRAnAXMFAgF1EgYAKQAA////5QAABGQHbRAnAXMDFgF1EgYASQAAAAIAyQAABosF1QATABcAAAEzFSE1MxUzFSMRIxEhESMRIzUzFxUhNQFxygLeyqioyv0iyqioygLeBdXg4OCk+68Cx/05BFGkpODgAAABAHgAAASfBhQAGwAAAREjETQmIyIGFREjESM1MzUzFSEVIRE+ATMyFgSfuHx8lay5fX25AWD+oEKzdcHGAqT9XAKen56+pP2HBPakenqk/rxlZO8A////5AAAAngHXhAnAXEDLgF1EgYAKgAA////0wAAAmcGNxAnAUf/HQAAEgYA8QAA//8AAwAAAlkHMRAnAG//LgE7EgYAKgAA////8gAAAkgF9RAnAG//Hf//EgYA8QAA////9QAAAmcHbRAnAXUDLgF1EgYAKgAA////5AAAAlYGSBAnAUT/HQAAEgYA8QAA//8AsP51AiUF1RAnAUb/ZAAAEgYAKgAA//8Alv51AgsGFBAnAUb/SgAAEgYASgAA//8AyQAAAZUHUBImACoAABAHAXYDLwF1AAIAwQAAAXkEewADAAQAABMzESMTwbi4XARg+6AEewD//wDJ/mYD7wXVECcAKwJcAAAQBgAqAAD//wDB/lYDsQYUECcASwI4AAAQBgBKAAD///+W/mYCXwdtECcBcwMuAXUSBgArAAD////b/lYCXAZmECcBQv8dAAASBgFAAAD//wDJ/h4FagXVECcBTAUbAAoSBgAsAAD//wC6/h4EnAYUECcBTASsAAoSBgBMAAAAAQC6AAAEnARgAAoAABMzEQEzCQEjAREjurkCJev9rgJr8P3HuQRg/hsB5f3y/a4CIf3f//8AyQAABGoHbBAnAXADbgF2EgYALQAA//8AwQAAAkoHbBAnAXADWgF2EgYATQAA//8Ayf4eBGoF1RAnAUwEmwAKEgYALQAA//8AiP4eAa0GFBAnAUwDHgAKEgYATQAA//8AyQAABGoF1RAnAW4Cn//DEgYALQAA//8AwQAAAwAGFBAnAW4COQACEAYATQAA//8AyQAABGoF1RAnAHcCMQB3EgYALQAA//8AwQAAAoQGFBAnAHcA1gBzEAYATQAAAAH/8gAABHUF1QANAAATMxElFwERIRUhEQcnN9PLATlQ/ncC1/xelE3hBdX9mNtv/u7946oCO2pungABAAIAAAJIBhQACwAAEzMRNxcHESMRByc3x7h9TMm4e0rFBhT9plpqjfzjAppYao0A//8AyQAABTMHbBAnAXAExQF2EgYALwAA//8AugAABGQGbRAmAHRCBxIGAE8AAP//AMn+HgUzBdUQJwFMBQAAChIGAC8AAP//ALr+HgRkBHsQJwFMBJAAChIGAE8AAP//AMkAAAUzB18SJgAvAAAQBwF0BPUBZ///ALoAAARkBmYSJgBPAAAQBwFDAI0AAP//AM0AAAW5BdUQJwBPAVUAABAGAUEbAAABAMn+VgUZBfAAHAAAARAhIgYVESMRMxU2NzYzMhIZARQHBisBNTMyNjUEUP7Ns9fKyk5papnj6VFStVcxZk8DfwGs/978sgXV8YZDQ/7B/sz8b9VhYJxaoAABALr+VgRkBHsAHwAAAREUBwYrATUzMjc2NRE0JiMiBhURIxEzFTY3NjMyFxYEZFJRtf7paSYmfHyVrLm5QlladcFjYwKk/UjWYGCcMDGZArKfnr6k/YcEYK5lMjJ3eP//AHP/4wXZBzEQJwBvAScBOxIGADAAAP//AHH/4wR1BfUQJgBvc/8SBgBQAAD//wBz/+MF2QdtECcBdQUnAXUSBgAwAAD//wBx/+MEdQZIECYBRHMAEgYAUAAA//8Ac//jBdkHaxAnAXcFJwF1EgYAMAAA//8Acf/jBHUGZhAnAUgAoAAAEgYAUAAAAAIAcwAACAwF1QAQABkAAAEVIREhFSERIRUhIAAREAAhFyMgABEQACEzB/r9GgLH/TkC+PvX/k/+QQG/AbFngf6//sABQAFBgQXVqv5Gqv3jqgF8AXABbQF8qv7h/uD+3/7fAAADAHH/4wfDBHsABgAnADMAAAEuASMiBgcFFSEeATMyNjcVDgEjIiYnDgEjIgAREAAzMhYXPgEzMgAlIgYVFBYzMjY1NCYHCgKkiZm5DgNI/LIMzLdqyGJk0Gqg8lFH0Yzx/u8BEfGM00JO6I/iAQj6sJSsq5WTrKwClJizrp41Wr7HNDSuKixubW5tATkBEwEUAThvbGtw/t2H58nJ5+jIx+kA//8AyQAABVQHbBAnAXAElQF2EgYAMwAA//8AugAAA5QGbRAmAHRCBxIGAFMAAP//AMn+HgVUBdUQJwFMBRAAChIGADMAAP//AIL+HgNKBHsQJwFMAxgAChIGAFMAAP//AMkAAAVUB18SJgAzAAAQBwF0BH0BZ///ALoAAANaBmYSJgBTAAAQBgFDGwD//wCH/+MEogdsECcBcASVAXYSBgA0AAD//wBv/+MDxwZtECYAdEIHEgYAVAAA//8Ah//jBKIHbRAnAXMEkwF1EgYANAAA//8Ab//jA8cGZhAmAUIlABIGAFQAAP//AIf+dQSiBfASJgA0AAAQBwB4AIsAAP//AG/+dQPHBHsSJgBUAAAQBgB4FwD//wCH/+MEogdtEiYANAAAEAcBdASLAXX//wBv/+MDxwZmEiYAVAAAEAcBSgQnAAD////6/nUE6QXVECYAeFAAEgYANQAA//8AN/51AvIFnhAmAHjhABIGAFUAAP////oAAATpB18SJgA1AAAQBwF0BHMBZ///ADcAAAL+BoISJgBVAAAQBwFuAjcAcAAB//oAAATpBdUADwAAAyEVIREhFSERIxEhNSERIQYE7/3uAQn+98v+9wEJ/e4F1ar9wKr9vwJBqgJAAAABADcAAALyBZ4AHQAAAREhFSEVIRUhFRQXFjsBFSMiJyY9ASM1MzUjNTMRAXcBe/6FAXv+hSUmc7291VFRh4eHhwWe/sKP6Y7piScnmlBP0umO6Y8BPgD//wCy/+MFKQdeECcBcQTuAXUSBgA2AAD//wCu/+MEWAY3ECcBRwCDAAASBgBWAAD//wCy/+MFKQcxECcAbwDuATsSBgA2AAD//wCu/+MEWAX1ECcAbwCD//8SBgBWAAD//wCy/+MFKQdtECcBdQTuAXUSBgA2AAD//wCu/+MEWAZIECcBRACDAAASBgBWAAD//wCy/+MFKQdvEiYANgAAEAcBRQDwAGn//wCu/+MEWAbKEiYAVgAAEAYBRXzE//8Asv/jBSkHaxAnAXcE7gF1EgYANgAA//8Arv/jBF4GZhAnAUgAsAAAEgYAVgAA//8Asv51BSkF1RImADYAABAHAUYA+gAA//8Arv51BOgEexImAFYAABAHAUYCJwAA//8ARAAAB6YHdBAnAXMF9QF8EgYAOAAA//8AVgAABjUGbRAnAUIBRQAHEgYAWAAA/////AAABOcHdBAnAXMEcgF8EgYAOgAA//8APf5WBH8GbRAmAUJeBxIGAFoAAP////wAAATnB04SJgA6AAAQBwFvBHMBdf//AFwAAAUfB2wQJwFwBJUBdhIGADsAAP//AFgAAAPbBm0QJgB0QgcSBgBbAAD//wBcAAAFHwdQECcBdgS+AXUSBgA7AAD//wBYAAAD2wYUECcBSQQXAAASBgBbAAD//wBcAAAFHwdtEiYAOwAAEAcBdAS+AXX//wBYAAAD2wZmEiYAWwAAEAYBQxsAAAEALwAAAvgGFAAQAAAhIxEjNTM1NDY7ARUjIgcGFQGYubCwrr2usGMnJgPRj067q5koKWcAAAH/2/5WAXkEYAALAAATMxEUBisBNTMyNjXBuKO1RjFpTARg+4zWwJxhmQD//wCyA/4B1wXVEAYBUAAAAAEAwQTuAz8GZgAGAAABMxMjJwcjAbaU9Yu0tIsGZv6I9fUAAAEAwQTuAz8GZgAGAAABAzMXNzMDAbb1i7S0i/UE7gF49fX+iAAAAQDHBSkDOQZIAA0AABMzHgEzMjY3Mw4BIyImx3YLYVdWYA12Cp6RkZ4GSEtLSkyPkJAAAAIA7gThAxIHBgALABcAAAE0JiMiBhUUFjMyNjcUBiMiJjU0NjMyFgKYWEBBV1dBQFh6n3Nzn59zc58F9D9YV0BBV1hAc6Cgc3OfnwABAUz+dQLBAAAAEwAAITMOARUUFjMyNjcVDgEjIiY1NDYBuHctKzc2ID4fJkQeenM1PVgfLi4PD4UKClddMGkAAQC2BR0DSgY3ABsAAAEnLgEjIgYHIz4BMzIWHwEeATMyNjczDgEjIiYB/DkWIQ0mJAJ9AmZbJkAlORYhDSYkAn0CZlsmQAVaNxQTSVKHkxwhNxQTSVKHkxwAAgDwBO4DrgZmAAMABwAAATMDIwMzAyMC/LL4h4Gq34kGZv6IAXj+iAAAAv2iBHv+WgYUAAMABAAAATMVIxf9ori4XgYU6bAAAvzFBHv/QwZmAAYABwAAAQMzFzczAwf9uvWLtLSL9U4E7gF49fX+iHMAAf4fA+n/RAUoAAMAAAEjEzP+8tOkgQPpAT8AAAH9av4U/o//VAADAAAFMwMj/bzTpIGs/sAAAQBkAekDnAJ5AAMAABMhFSFkAzj8yAJ5kAABAGQB6QecAnkAAwAAEyEVIWQHOPjIAnmQAAEArgPpAdMF1QAFAAABIzUTMwMBgdOkgVID6a0BP/7BAAABALID/gHXBdUABQAAATMVAyMTAQTTpIFSBdWY/sEBPwAAAQCu/xIB0wD+AAUAACUzFQMjEwEA06SBUv6s/sABQAACAK4D6QNtBdUABQALAAABIzUTMwMFIzUTMwMBgdOkgVIBmtOkgVID6a0BP/7Bra0BP/7BAAACAK4D6QNtBdUABQALAAABMxUDIxMlMxUDIxMBANOkgVIBmtOkgVIF1az+wAFArKz+wAFAAAACAK7/EgNtAP4ABQALAAAlMxUDIxMlMxUDIxMCmtOkgVL+ZtOkgVL+rP7AAUCsrP7AAUAAAQEzAdEDhQQhAAsAAAE0NjMyFhUUBiMiJgEzrX58q6x9fawC+nyrq3x9rKwAAAMA7AAABxQA/gADAAcACwAAJTMVIyUzFSMlMxUjA5bU1AKp1dX6rdXV/v7+/v7+AAH+if/jAs0F8AADAAABMwEjAi2g/FygBfD58wACAD8CnAL0Bd8AAgANAAAJASEDMxEzFSMVIzUhNQHd/ssBNRamh4eQ/mIFZv5dAhz95G26unkAAAEAAP/jBI8F8AAxAAABFS4BIyIGByEHIQ4BFRQWFyEHIR4BMzI2NxUOASMiAAMjNzM0JjU0NjUjNzMSADMyFgSPW6lmncogAkE3/eYCAQECAb44/oogyp1mqVtZuWDt/sso0zeLAQHCN5woATbsYrkFYtVpWsi7exguIyAuGHu7ylpp00hIASIBA3sXLyAjLxd7AQEBIkcAAQDZAi0F2wLXAAMAABMhFSHZBQL6/gLXqgABALD9/ANQB5IACwAAASM1EBMSEzMAAwIRAXPDoLqmoP78Wn/9/OoDlwHiAjABA/3z/ob97vztAAEAsP38AXMHiQADAAATMxEjsMPDB4n2cwAAAQCw/hQDUAeJAAsAAAEVEBMSEyMCAwIRNQFzf5PLoNCQoAeJ6vyl/lf+FP5lAUUB7gImAzLqAAABALD9/ANQB5IACwAAATUQAwIBMxITEhEVAo1/Wv78oKa6oP386gMTAhIBeQIO/v390P4e/GnqAAECjf38A1AHiQAEAAABESMRMANQwweJ9nMJjQABALD+FANQB4kACwAAATMVEAMCAyMSExIRAo3DoJDQoMuTfweJ6vzN/dv+Ev67AZsB7AGpA1sAAAEAsP38A1AHbQAFAAABIxEhFSEBc8MCoP4j/fwJccMAAQCw/fwBcweJAAMAABMzESOww8MHifZzAAABALD+FANQB4kABQAAAREhFSERAXMB3f1gB4n3TsMJdQAAAQCw/fwDUAdtAAUAAAERITUhEQKN/iMCoP38CK7D9o8AAAECjf38A1AHegADAAABMxEjAo3Dwwd69oIAAQCw/hQDUAd6AAUAAAEzESE1IQKNw/1gAd0HevaawwABAqP96gVYB20ADQAAASMRNDc2MyEVISIHBhUDXbpveboBE/7nZUQ5/eoHdd+RnrBmV5kAAQCo/fwDXQeGABgAAAEWFxYZASMRECcmJSc1MyA3NhkBMxEQBwYClDoqZbpuS/77PT0BA01uumUoAsEgPZP+Q/3oAgwBt19BBAG7RWMBswIM/ej+SJg8AAECo/4UBVgHhgANAAABERQXFjMhFSEiJyY1EQNdOURlARn+7bh7bweG+JSaVmawno/hB2QAAAECo/30A10HjAADAAABIxEzA126uv30CZgAAQCo/eoDXQdtAA0AAAERNCcmIyE1ITIXFhURAqM5RGX+5wETunlv/eoHfZlXZrCekd/4iwAAAQKj/fwFWAeGABgAAAEmJyYZATMREBcWITMVBwQHBhkBIxEQNzYDbDwoZbpuTQEDPT3++0tuumUqAsEhPJgBuAIY/fT+TWNFuwEEQV/+Sf30AhgBvZM9AAEAqP4UA10HhgANAAABMxEUBwYjITUhMjc2NQKjum97uP7tARllRDkHhvic4Y+esGZWmgAB/7kEmgDHBhIAAwAAETMDI8d1mQYS/ogAAAL81wUO/ykF2QADAAcAAAEzFSMlMxUj/l7Ly/55y8sF2cvLywAAAf1zBO7+8AX2AAMAAAEzAyP+N7nkmQX2/vgAAAH8tgUO/0oF6QAdAAABJy4BIyIGHQEjNDYzMhYfAR4BMzI2PQEzDgEjIib9/DkZHwwkKH1nViQ9MDkXIg8gKH0CZ1QiOwU5IQ4LMi0GZXYQGx4NDDMpBmR3EAAAAf0MBO7+iwX2AAMAAAETIwP9x8SZ5gX2/vgBCAAAAfzPBO7/MQX4AAYAAAEzEyMnByP9orzTi6amiwX4/vaysgAAAfzPBO7/MQX4AAYAAAEDMxc3MwP9otOLpqaL0wTuAQqysv72AAAB/McFBv85BfgADQAAATMeATMyNjczDgEjIib8x3YNY1NSYRB2CqCPkJ8F+DY5Nzh3e3oAAf2aBQ7+ZgXbAAMAAAEzFSP9mszMBdvNAAAC/OYE7v+yBfYAAwAHAAABMwMjAzMDI/75ueSZi7nkmQX2/vgBCP74AAABAAABeANUACsAaAAMAAEAAAAAAAAAAAAAAAAACAAEAAAAAAAAABYAKgBmALIBAAFOAVwBeQGVAbsB1AHkAfEB/QILAjsCUgKCAr4C2wMLA0oDXQOlA+MD9AQKBB8EMgRGBH8E9AUQBUcFdwWfBbcFzAYDBhsGKAY+BlkGaQaHBp8G0wb2BzMHZAehB7QH1gfrCAsIKghBCFgIagh5CIsIoQiuCL4I9gkmCVIJggm0CdQKEwo1CkcKYgp8CokKvQreCwoLOgtqC4kLxAvlDAkMHQw6DFoMeQyQDMIM0A0CDTINMg1JDYYNsQ37DikOPg6ZDqwPGw9aD3wPjA+ZEA8QHBBHEGcQkRDLENkRCxEmETIRUxFpEZYRuhHKEdoR6hIjEi8SOxJHElMSXxKZEsESzRLZEuUS8RL9EwkTFRMhEy0TXxNrE3cTgxOPE5sTpxPJFBYUIhQuFDoURhRSFHcUvRTIFNMU3hTpFPQU/xVbFWcVcxV/FYsVlxWjFa8VuxXHFgwWGBYjFi4WORZEFk8WaRaxFrwWxxbSFt0W6BcYFyMXLxc6F0YXURddF2kXdReBF40XmRelF7EXvRfJF9UX4RfpGCIYLhg6GEYYUhheGGoYdhiCGI4YmhimGLEYvRjJGNUY4RjtGPkZBRkRGTcZYhluGXoZhhmSGZ4Zqhm2GcIZzhneGeoZ9hoCGg4aGhomGkAaTBpYGmQacBp8GogalBqgGr0a1hriGu0a+RsFGxEbHRspG1YbhhuSG50bqRu0G8AbzBv+HFAcXBxnHHMcfxyLHJYcohytHLkcxBzQHNsc5xzzHP4dCR0VHSEdPx1rHXcdgx2PHZsdpx2zHb8dyh3WHeId7h36HgYeEh4eHikeNR5BHkweWB5kHnAeex6WHqwetB7GHtke8x8ZHzkfZh97H4ofnx+tH7ofxx/UH+Uf9iAGICEgPCBWIG0ghSCTIK8g+yEIISQhMSFNIWkhdyGTIaMhsCHBIdIh3yHvIgkiNSJQIl0ieCKkIr4iyyLeIuwjGiMpIzsjTiNoI3UjigAAAAEAAAACXrgD75HxXw889QAfCAAAAAAA4PrROQAAAADg+tE599b8TA5ZCdwAAAAIAAIAAAAAAAAEzQBmAosAAAM1ATUDrgDFBrQAngUXAKoHmgBxBj0AgQIzAMUDHwCwAx8ApAQAAD0GtADZAosAngLjAGQCiwDbArIAAAUXAIcFFwDhBRcAlgUXAJwFFwBkBRcAngUXAI8FFwCoBRcAiwUXAIECsgDwArIAnga0ANkGtADZBrQA2QQ/AJMIAACHBXkAEAV9AMkFlgBzBikAyQUOAMkEmgDJBjMAcwYEAMkCXADJAlz/lgU/AMkEdQDJBucAyQX8AMkGTABzBNMAyQZMAHMFjwDJBRQAhwTj//oF2wCyBXkAEAfpAEQFewA9BOP//AV7AFwDHwCwArIAAAMfAMcGtADZBAD/7AQAAKoE5wB7BRQAugRmAHEFFABxBOwAcQLRAC8FFABxBRIAugI5AMECOf/bBKIAugI5AMEHywC6BRIAugTlAHEFFAC6BRQAcQNKALoEKwBvAyMANwUSAK4EvAA9BosAVgS8ADsEvAA9BDMAWAUXAQACsgEEBRcBAAa0ANkCiwAAAzUBNQUXAKwFFwCBBRcAXgUXAFICsgEEBAAAXAQAANcIAAEbA8UAcwTlAJ4GtADZAuMAZAgAARsEAADVBAAAwwa0ANkDNQBeAzUAYgQAAXMFFwCuBRcAngKLANsEAAEjAzUAiQPFAGAE5QDBB8EAiQfBAIkHwQBiBD8AjwV5ABAFeQAQBXkAEAV5ABAFeQAQBXkAEAfLAAgFlgBzBQ4AyQUOAMkFDgDJBQ4AyQJcADsCXACiAlz//gJcAAYGMwAKBfwAyQZMAHMGTABzBkwAcwZMAHMGTABzBrQBGQZMAGYF2wCyBdsAsgXbALIF2wCyBOP//ATXAMkFCgC6BOcAewTnAHsE5wB7BOcAewTnAHsE5wB7B9sAewRmAHEE7ABxBOwAcQTsAHEE7ABxAjn/xwI5AJACOf/eAjn/9ATlAHEFEgC6BOUAcQTlAHEE5QBxBOUAcQTlAHEGtADZBOUASAUSAK4FEgCuBRIArgUSAK4EvAA9BRQAugS8AD0FeQAQBOcAewV5ABAE5wB7BXkAEATnAHsFlgBzBGYAcQWWAHMEZgBxBZYAcwRmAHEFlgBzBGYAcQYpAMkFFABxBjMACgUUAHEFDgDJBOwAcQUOAMkE7ABxBQ4AyQTsAHEFDgDJBOwAcQUOAMkE7ABxBjMAcwUUAHEGMwBzBRQAcQYzAHMFFABxBjMAcwUUAHEGBADJBRL/5QdUAMkFjwB4Alz/5AI5/9MCXAADAjn/8gJc//UCOf/kAlwAsAI5AJYCXADJAjkAwQS4AMkEcgDBAlz/lgI5/9sFPwDJBKIAugSiALoEdQDJAjkAwQR1AMkCOQCIBHUAyQMAAMEEdQDJArwAwQR///ICRgACBfwAyQUSALoF/ADJBRIAugX8AMkFEgC6BoIAzQX8AMkFEgC6BkwAcwTlAHEGTABzBOUAcQZMAHME5QBxCI8AcwgvAHEFjwDJA0oAugWPAMkDSgCCBY8AyQNKALoFFACHBCsAbwUUAIcEKwBvBRQAhwQrAG8FFACHBCsAbwTj//oDIwA3BOP/+gMjADcE4//6AyMANwXbALIFEgCuBdsAsgUSAK4F2wCyBRIArgXbALIFEgCuBdsAsgUSAK4F2wCyBRIArgfpAEQGiwBWBOP//AS8AD0E4//8BXsAXAQzAFgFewBcBDMAWAV7AFwEMwBYAtEALwI5/9sCiwCyBAAAwQQAAMEEAADHBAAA7gQAAUwEAAC2BAAA8AAA/aIAAPzFAAD+HwAA/WoEAABkCAAAZAKLAK4CiwCyAosArgQlAK4EJQCuBCUArgS4ATMIAADsAVb+iQM1AD8FFwAABrQA2QQAALAEAACwBAAAsAQAALAEAAKNBAAAsAQAALAEAACwBAAAsAQAALAEAAKNBAAAsAYAAqMGAACoBgACowYAAqMGAACoBgACowYAAKgAAP+5/Nf9c/y2/Qz8z/zP/Mf9mvzmAAAAAQAAB23+HQAADv731vpRDlkAAQAAAAAAAAAAAAAAAAAAAW8AAQQOAZAABQAABTMFmQAAAR4FMwWZAAAD1wBmAhIAAAILBgMDCAQCAgSAAAAHAAAAQgAAAAAAAAAAUGZFZABAACAiEgYU/hQBmgdtAeMAAACTAAAAAAAAAAAAAgAAAAMAAAAUAAMAAQAAABQABABgAAAAFAAQAAMABAB+AX8gFCAaIB4gIiAmIKwiEv//AAAAIACgIBMgGCAcICIgJiCsIhL////h/8DhOuE34TbhM+Ew4K3fSAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAFoAAwABBAkAAAEwAAAAAwABBAkAAQAWATAAAwABBAkAAgAIAUYAAwABBAkAAwAWATAAAwABBAkABAAWATAAAwABBAkABQAYAU4AAwABBAkABgAUAWYAQwBvAHAAeQByAGkAZwBoAHQAIAAoAGMAKQAgADIAMAAwADMAIABiAHkAIABCAGkAdABzAHQAcgBlAGEAbQAsACAASQBuAGMALgAgAEEAbABsACAAUgBpAGcAaAB0AHMAIABSAGUAcwBlAHIAdgBlAGQALgAKAEMAbwBwAHkAcgBpAGcAaAB0ACAAKABjACkAIAAyADAAMAA2ACAAYgB5ACAAVABhAHYAbQBqAG8AbgBnACAAQgBhAGgALgAgAEEAbABsACAAUgBpAGcAaAB0AHMAIABSAGUAcwBlAHIAdgBlAGQALgAKAEQAZQBqAGEAVgB1ACAAYwBoAGEAbgBnAGUAcwAgAGEAcgBlACAAaQBuACAAcAB1AGIAbABpAGMAIABkAG8AbQBhAGkAbgAKAEQAZQBqAGEAVgB1ACAAUwBhAG4AcwBCAG8AbwBrAFYAZQByAHMAaQBvAG4AIAAyAC4AMwA3AEQAZQBqAGEAVgB1AFMAYQBuAHMAAwAAAAAAAP/YAFoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACAAC//8AAwABAAAACgDgAOgAUAA8DAAH3QAAAAACggAABGAAAAXVAAAAAAAABGAAAAAAAAAAAAAAAAAAAARgAAAAAAAAAWgAAARgAAAAVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABDgAAAnYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoAAAEOAAAAWgAAAFoAAAEOAAAAAAAAAAAAAAEOAAAAWgAAAFoAAAEOAAAAWgAAAFoAAABaAAABcgAAAFoAAABaAAACOAAA+48AAAA8AAAAAAAAAAAAKAAeADAABwADADoAYgCKALIA2gEWATQBcAGOAawAAQAHAAkACgA8AD4AXABdAF4AAQADAB4AQABvAAQAAAAAAAAAAwFdAAAAKAl1AAABXAAoACgJjQABAVsAKAAACZYAAAAEAAAAAAAAAAMBYAAAACgJdQAAAV8AKAAoCY0AAQFeACgAAAmWAAAABAAAAAAAAAADAWMAAAAoCXUAAAFiACgAKAmNAAEBYQAoAAAJcQAAAAQAAAAAAAAAAwFmAAAAKAlmAAABZQAoACgJfgABAWQAKAAACXEAAAAEAAAAAAAAAAUBaQAAACgJcgAAAWoAKAAoCZgAAQFoACgAKAmKAAABagAoACgJmAABAWcAKAAACYMAAAAEAAAAAAAAAAIAXQAAACgIAAAAAF0AKAAACAAAAQAEAAAAAAAAAAUBbQAAACgJcgAAAWoAKAAoCZgAAQFsACgAKAmKAAABagAoACgJmAABAWsAKAAACYMAAAAEAAAAAAAAAAIAHgAAACgFAgAAAB4AKAAABQIAAQAEAAAAAAAAAAIAQAAAACgEKAAAAEAAKAAABCgAAQAEAAAAAAAAAAIAbwAAACgCVgAAAG8AKAAAAlYAAQAA';
  function b64ToBytes(b64) {
    var bin = atob(b64), n = bin.length, out = new Uint8Array(n);
    for (var i = 0; i < n; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // ── Preprost razčlenjevalnik TTF (head, maxp, hhea, hmtx, cmap format 4) ──
  function TTF(bytes) {
    var dv = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    this.dv = dv; this.bytes = bytes;
    var numTables = dv.getUint16(4), off = 12, tab = {};
    for (var i = 0; i < numTables; i++) {
      var tag = String.fromCharCode(bytes[off], bytes[off + 1], bytes[off + 2], bytes[off + 3]);
      tab[tag] = { off: dv.getUint32(off + 8), len: dv.getUint32(off + 12) };
      off += 16;
    }
    this.tab = tab;
    var head = tab.head.off;
    this.unitsPerEm = dv.getUint16(head + 18);
    this.xMin = dv.getInt16(head + 36); this.yMin = dv.getInt16(head + 38);
    this.xMax = dv.getInt16(head + 40); this.yMax = dv.getInt16(head + 42);
    this.numGlyphs = dv.getUint16(tab.maxp.off + 4);
    this.numH = dv.getUint16(tab.hhea.off + 34);
    this.ascent = dv.getInt16(tab.hhea.off + 4); this.descent = dv.getInt16(tab.hhea.off + 6);
    this._parseCmap();
    this._adv = new Array(this.numGlyphs);
    var hm = tab.hmtx.off, last = 0;
    for (var g = 0; g < this.numGlyphs; g++) {
      if (g < this.numH) { last = dv.getUint16(hm + g * 4); }
      this._adv[g] = last;
    }
  }
  TTF.prototype._parseCmap = function () {
    var dv = this.dv, base = this.tab.cmap.off, nt = dv.getUint16(base + 2), sub = -1;
    for (var i = 0; i < nt; i++) {
      var pid = dv.getUint16(base + 4 + i * 8), eid = dv.getUint16(base + 6 + i * 8), o = dv.getUint32(base + 8 + i * 8);
      if ((pid === 3 && (eid === 1 || eid === 0)) || pid === 0) { sub = base + o; if (pid === 3 && eid === 1) break; }
    }
    var s = sub, fmt = dv.getUint16(s);
    this._cmap = {};
    if (fmt !== 4) return;
    var segX2 = dv.getUint16(s + 6), segCount = segX2 / 2;
    var endO = s + 14, startO = endO + segX2 + 2, deltaO = startO + segX2, rangeO = deltaO + segX2;
    for (var j = 0; j < segCount; j++) {
      var end = dv.getUint16(endO + j * 2), start = dv.getUint16(startO + j * 2);
      var delta = dv.getUint16(deltaO + j * 2), ro = dv.getUint16(rangeO + j * 2);
      for (var c = start; c <= end && c !== 0xFFFF; c++) {
        var gid;
        if (ro === 0) { gid = (c + delta) & 0xFFFF; }
        else {
          var gi = rangeO + j * 2 + ro + (c - start) * 2;
          gid = dv.getUint16(gi); if (gid !== 0) gid = (gid + delta) & 0xFFFF;
        }
        if (gid) this._cmap[c] = gid;
      }
    }
  };
  TTF.prototype.gid = function (cp) { return this._cmap[cp] || 0; };
  TTF.prototype.adv1000 = function (gid) { return Math.round(this._adv[gid] * 1000 / this.unitsPerEm); };

  var FONT = new TTF(b64ToBytes(FONT_B64));

  // ── PDF dokument ──────────────────────────────────────────────────────
  function PDFDoc(opt) {
    opt = opt || {};
    this.W = opt.width || 595.28; this.H = opt.height || 841.89;   // A4 v točkah
    this.pages = []; this.cur = null;
    this.images = [];   // {bytes,w,h}
    this._seenGid = {};
  }
  PDFDoc.prototype.addPage = function () { this.cur = { ops: [] }; this.pages.push(this.cur); return this; };
  PDFDoc.prototype._enc = function (str) {
    var out = '', s = String(str == null ? '' : str);
    for (var i = 0; i < s.length; i++) {
      var cp = s.charCodeAt(i);
      // združi surogate (izven BMP) — redko; drugače uporabi znak
      if (cp >= 0xD800 && cp <= 0xDBFF && i + 1 < s.length) { var lo = s.charCodeAt(i + 1); cp = ((cp - 0xD800) * 0x400) + (lo - 0xDC00) + 0x10000; i++; }
      var g = FONT.gid(cp); if (!g) g = FONT.gid(0x20);
      this._seenGid[g] = 1;
      out += ('000' + g.toString(16)).slice(-4);
    }
    return out;
  };
  PDFDoc.prototype.width = function (str, size) {
    var s = String(str == null ? '' : str), w = 0;
    for (var i = 0; i < s.length; i++) {
      var cp = s.charCodeAt(i);
      if (cp >= 0xD800 && cp <= 0xDBFF && i + 1 < s.length) { var lo = s.charCodeAt(i + 1); cp = ((cp - 0xD800) * 0x400) + (lo - 0xDC00) + 0x10000; i++; }
      w += FONT.adv1000(FONT.gid(cp) || FONT.gid(0x20));
    }
    return w * size / 1000;
  };
  function fmt(n) { return (Math.round(n * 100) / 100).toString(); }
  PDFDoc.prototype.text = function (x, yTop, str, o) {
    o = o || {}; var size = o.size || 10, col = o.color || [0.09, 0.13, 0.17];
    var w = this.width(str, size);
    if (o.align === 'right') x -= w; else if (o.align === 'center') x -= w / 2;
    var y = this.H - yTop;   // yTop = odmik osnovne črte od vrha
    var t = 'BT /F1 ' + fmt(size) + ' Tf ' + fmt(col[0]) + ' ' + fmt(col[1]) + ' ' + fmt(col[2]) + ' rg ';
    if (o.bold) { t += '2 Tr ' + fmt(size * 0.028) + ' w ' + fmt(col[0]) + ' ' + fmt(col[1]) + ' ' + fmt(col[2]) + ' RG '; }
    t += '1 0 0 1 ' + fmt(x) + ' ' + fmt(y) + ' Tm <' + this._enc(str) + '> Tj ';
    if (o.bold) t += '0 Tr ';
    t += 'ET';
    this.cur.ops.push(t);
    return w;
  };
  PDFDoc.prototype.line = function (x1, y1, x2, y2, o) {
    o = o || {}; var c = o.color || [0.85, 0.9, 0.88];
    this.cur.ops.push(fmt(c[0]) + ' ' + fmt(c[1]) + ' ' + fmt(c[2]) + ' RG ' + fmt(o.width || 0.7) + ' w ' +
      fmt(x1) + ' ' + fmt(this.H - y1) + ' m ' + fmt(x2) + ' ' + fmt(this.H - y2) + ' l S');
  };
  PDFDoc.prototype.rect = function (x, yTop, w, h, o) {
    o = o || {}; var y = this.H - (yTop + h), s = '';
    if (o.fill) { s += fmt(o.fill[0]) + ' ' + fmt(o.fill[1]) + ' ' + fmt(o.fill[2]) + ' rg '; }
    if (o.stroke) { s += fmt(o.stroke[0]) + ' ' + fmt(o.stroke[1]) + ' ' + fmt(o.stroke[2]) + ' RG ' + fmt(o.width || 0.7) + ' w '; }
    s += fmt(x) + ' ' + fmt(y) + ' ' + fmt(w) + ' ' + fmt(h) + ' re ' + (o.fill && o.stroke ? 'B' : o.fill ? 'f' : 'S');
    this.cur.ops.push(s);
  };
  // jpegBytes: Uint8Array (JPEG); w,h v točkah; xTop,yTop odmik od vrha levo
  PDFDoc.prototype.image = function (jpegBytes, x, yTop, w, h, iw, ih) {
    var idx = this.images.length; this.images.push({ bytes: jpegBytes, w: iw, h: ih });
    var y = this.H - (yTop + h);
    this.cur.ops.push('q ' + fmt(w) + ' 0 0 ' + fmt(h) + ' ' + fmt(x) + ' ' + fmt(y) + ' cm /Im' + idx + ' Do Q');
  };
  // ── izpis PDF v bajte ──
  function bytesFromLatin1(str) { var n = str.length, a = new Uint8Array(n); for (var i = 0; i < n; i++) a[i] = str.charCodeAt(i) & 0xFF; return a; }
  PDFDoc.prototype.build = function () {
    var chunks = [], offsets = [], pos = 0, self = this;
    function push(x) { var b = (x instanceof Uint8Array) ? x : bytesFromLatin1(x); chunks.push(b); pos += b.length; }
    var objs = [];   // vsak: function or string producing body; zbrano spodaj
    // Rezervramo številke objektov
    var oCatalog = 1, oPages = 2, oFont = 3, oCID = 4, oFD = 5, oFontFile = 6;
    var oFirstImg = 7, nImg = this.images.length;
    var oFirstPage = oFirstImg + nImg;         // page obj
    var oFirstContent = oFirstPage + this.pages.length;
    var total = oFirstContent + this.pages.length - 1;
    var body = {};
    // W (širine) za vse glife
    var W = '[0 ['; for (var g = 0; g < FONT.numGlyphs; g++) { W += FONT.adv1000(g) + (g < FONT.numGlyphs - 1 ? ' ' : ''); } W += ']]';
    var upm = FONT.unitsPerEm, sc = 1000 / upm;
    var bbox = [Math.round(FONT.xMin * sc), Math.round(FONT.yMin * sc), Math.round(FONT.xMax * sc), Math.round(FONT.yMax * sc)];
    body[oCatalog] = '<< /Type /Catalog /Pages ' + oPages + ' 0 R >>';
    var kids = ''; for (var p = 0; p < this.pages.length; p++) kids += (oFirstPage + p) + ' 0 R ';
    body[oPages] = '<< /Type /Pages /Count ' + this.pages.length + ' /Kids [' + kids + '] >>';
    body[oFont] = '<< /Type /Font /Subtype /Type0 /BaseFont /SCFont /Encoding /Identity-H /DescendantFonts [' + oCID + ' 0 R] >>';
    body[oCID] = '<< /Type /Font /Subtype /CIDFontType2 /BaseFont /SCFont /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor ' + oFD + ' 0 R /CIDToGIDMap /Identity /DW ' + FONT.adv1000(FONT.gid(0x20)) + ' /W ' + W + ' >>';
    body[oFD] = '<< /Type /FontDescriptor /FontName /SCFont /Flags 4 /FontBBox [' + bbox.join(' ') + '] /ItalicAngle 0 /Ascent ' + Math.round(FONT.ascent * sc) + ' /Descent ' + Math.round(FONT.descent * sc) + ' /CapHeight ' + Math.round(FONT.ascent * sc) + ' /StemV 88 /FontFile2 ' + oFontFile + ' 0 R >>';
    // objekti se zapišejo spodaj v vrstnem redu 1..total
    function writeObj(num, headStr, streamBytes) {
      offsets[num] = pos;
      push(num + ' 0 obj\n' + headStr);
      if (streamBytes != null) { push('\nstream\n'); push(streamBytes); push('\nendstream'); }
      push('\nendobj\n');
    }
    // Header
    push('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n');
    writeObj(oCatalog, body[oCatalog]);
    writeObj(oPages, body[oPages]);
    writeObj(oFont, body[oFont]);
    writeObj(oCID, body[oCID]);
    writeObj(oFD, body[oFD]);
    // FontFile2
    writeObj(oFontFile, '<< /Length ' + FONT.bytes.length + ' /Length1 ' + FONT.bytes.length + ' >>', FONT.bytes);
    // slike
    for (var im = 0; im < nImg; im++) {
      var img = this.images[im];
      writeObj(oFirstImg + im, '<< /Type /XObject /Subtype /Image /Width ' + img.w + ' /Height ' + img.h + ' /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ' + img.bytes.length + ' >>', img.bytes);
    }
    // strani + vsebine
    var xobj = ''; for (var k = 0; k < nImg; k++) xobj += '/Im' + k + ' ' + (oFirstImg + k) + ' 0 R ';
    for (var pi = 0; pi < this.pages.length; pi++) {
      var contentNum = oFirstContent + pi, pageNum = oFirstPage + pi;
      var stream = this.pages[pi].ops.join('\n');
      var sb = bytesFromLatin1(stream);
      writeObj(pageNum, '<< /Type /Page /Parent ' + oPages + ' 0 R /MediaBox [0 0 ' + fmt(this.W) + ' ' + fmt(this.H) + '] /Resources << /Font << /F1 ' + oFont + ' 0 R >> /XObject << ' + xobj + '>> >> /Contents ' + contentNum + ' 0 R >>');
      writeObj(contentNum, '<< /Length ' + sb.length + ' >>', sb);
    }
    // xref
    var xrefPos = pos;
    var count = total + 1;
    var xref = 'xref\n0 ' + count + '\n0000000000 65535 f \n';
    for (var n = 1; n <= total; n++) { var o = offsets[n] || 0; xref += ('0000000000' + o).slice(-10) + ' 00000 n \n'; }
    push(xref);
    push('trailer\n<< /Size ' + count + ' /Root ' + oCatalog + ' 0 R >>\nstartxref\n' + xrefPos + '\n%%EOF');
    // združi
    var totalLen = 0; chunks.forEach(function (c) { totalLen += c.length; });
    var out = new Uint8Array(totalLen), p2 = 0;
    chunks.forEach(function (c) { out.set(c, p2); p2 += c.length; });
    return out;
  };
  PDFDoc.prototype.save = function (ime) {
    var bytes = this.build();
    var blob = new Blob([bytes], { type: 'application/pdf' });
    var a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = ime;
    document.body.appendChild(a); a.click();
    setTimeout(function () { document.body.removeChild(a); URL.revokeObjectURL(a.href); }, 100);
  };
  // Pretvori data:image/png (ali katerokoli sliko) v JPEG bajte + dimenzije (Promise).
  PDFDoc.imageToJpeg = function (src, maxW) {
    return new Promise(function (resolve, reject) {
      var img = new Image();
      img.onload = function () {
        var scale = (maxW && img.width > maxW) ? maxW / img.width : 1;
        var w = Math.max(1, Math.round(img.width * scale)), h = Math.max(1, Math.round(img.height * scale));
        var cv = document.createElement('canvas'); cv.width = w; cv.height = h;
        var ctx = cv.getContext('2d'); ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, w, h); ctx.drawImage(img, 0, 0, w, h);
        try {
          var url = cv.toDataURL('image/jpeg', 0.92), b64 = url.split(',')[1];
          resolve({ bytes: b64ToBytes(b64), w: w, h: h });
        } catch (e) { reject(e); }
      };
      img.onerror = reject; img.src = src;
    });
  };
  window.PDFDoc = PDFDoc;
})();
